// <auto-generated />
using System;
using Etrx.Persistence.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Etrx.Persistence.Migrations
{
    [DbContext(typeof(EtrxDbContext))]
    [Migration("20251126150204_AddTagComplexity")]
    partial class AddTagComplexity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Etrx.Domain.Entities.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer");

                    b.Property<Guid>("GuidContestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuidContestId");

                    b.HasIndex("ContestId", "Index")
                        .IsUnique();

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("Etrx.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Complexity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Etrx.Domain.Models.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("Frozen")
                        .HasColumnType("boolean");

                    b.Property<bool>("Gym")
                        .HasColumnType("boolean");

                    b.Property<string>("IcpcRegion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsContestLoaded")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreparedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RelativeTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContestId")
                        .IsUnique();

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Etrx.Domain.Models.ContestTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContestId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ContestTranslations");
                });

            modelBuilder.Entity("Etrx.Domain.Models.ProblemResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long?>("BestSubmissionTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Penalty")
                        .HasColumnType("integer");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<Guid>("RanklistRowId")
                        .HasColumnType("uuid");

                    b.Property<int>("RejectedAttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RanklistRowId", "Index")
                        .IsUnique();

                    b.ToTable("ProblemResults");
                });

            modelBuilder.Entity("Etrx.Domain.Models.ProblemTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ProblemTranslations");
                });

            modelBuilder.Entity("Etrx.Domain.Models.RanklistRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("LastSubmissionTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer");

                    b.Property<double>("Points")
                        .HasColumnType("double precision");

                    b.Property<int>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulHackCount")
                        .HasColumnType("integer");

                    b.Property<int>("UnsuccessfulHackCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Handle", "ContestId", "ParticipantType")
                        .IsUnique();

                    b.ToTable("RanklistRows");
                });

            modelBuilder.Entity("Etrx.Domain.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer");

                    b.Property<long>("CreationTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("MemoryConsumedBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PassedTestCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProgrammingLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RelativeTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SubmissionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Testset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeConsumedMillis")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Verdict")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Etrx.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Contribution")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FriendOfCount")
                        .HasColumnType("integer");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LastOnlineTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("MaxRank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxRating")
                        .HasColumnType("integer");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<long>("RegistrationTimeSeconds")
                        .HasColumnType("bigint");

                    b.Property<string>("TitlePhoto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VkId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Handle")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProblemTag", b =>
                {
                    b.Property<Guid>("ProblemsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid");

                    b.HasKey("ProblemsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("ProblemTag");
                });

            modelBuilder.Entity("Etrx.Domain.Entities.Problem", b =>
                {
                    b.HasOne("Etrx.Domain.Models.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("GuidContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("Etrx.Domain.Models.ContestTranslation", b =>
                {
                    b.HasOne("Etrx.Domain.Models.Contest", null)
                        .WithMany("ContestTranslations")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Etrx.Domain.Models.ProblemResult", b =>
                {
                    b.HasOne("Etrx.Domain.Models.RanklistRow", null)
                        .WithMany("ProblemResults")
                        .HasForeignKey("RanklistRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Etrx.Domain.Models.ProblemTranslation", b =>
                {
                    b.HasOne("Etrx.Domain.Entities.Problem", null)
                        .WithMany("ProblemTranslations")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Etrx.Domain.Models.Submission", b =>
                {
                    b.HasOne("Etrx.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProblemTag", b =>
                {
                    b.HasOne("Etrx.Domain.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Etrx.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Etrx.Domain.Entities.Problem", b =>
                {
                    b.Navigation("ProblemTranslations");
                });

            modelBuilder.Entity("Etrx.Domain.Models.Contest", b =>
                {
                    b.Navigation("ContestTranslations");
                });

            modelBuilder.Entity("Etrx.Domain.Models.RanklistRow", b =>
                {
                    b.Navigation("ProblemResults");
                });
#pragma warning restore 612, 618
        }
    }
}
