// <auto-generated />
using System;
using Etrx.Persistence.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Etrx.Persistence.Migrations
{
    [DbContext(typeof(EtrxDbContext))]
    [Migration("20251206132356_AddTagsAndRelations")]
    partial class AddTagsAndRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Etrx.Domain.Models.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer")
                        .HasColumnName("difficulty");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("Frozen")
                        .HasColumnType("boolean")
                        .HasColumnName("frozen");

                    b.Property<bool>("Gym")
                        .HasColumnType("boolean")
                        .HasColumnName("gym");

                    b.Property<string>("IcpcRegion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("icpc_region");

                    b.Property<bool>("IsContestLoaded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_contest_loaded");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<string>("PreparedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prepared_by");

                    b.Property<long>("RelativeTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("relative_time_seconds");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("season");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint")
                        .HasColumnName("start_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_contests");

                    b.HasIndex("ContestId")
                        .IsUnique()
                        .HasDatabaseName("ix_contests_contest_id");

                    b.ToTable("contests", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.ContestTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("contest_id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_contest_translations");

                    b.HasIndex("ContestId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_contest_translations_contest_id_language_code");

                    b.ToTable("contest_translations", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<Guid>("GuidContestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guid_contest_id");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("index");

                    b.Property<double>("Points")
                        .HasColumnType("double precision")
                        .HasColumnName("points");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<int>("SolvedCount")
                        .HasColumnType("integer")
                        .HasColumnName("solved_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("GuidContestId")
                        .HasDatabaseName("ix_problems_guid_contest_id");

                    b.HasIndex("ContestId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_contest_id_index");

                    b.ToTable("problems", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.ProblemResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long?>("BestSubmissionTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("best_submission_time_seconds");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("index");

                    b.Property<int?>("Penalty")
                        .HasColumnType("integer")
                        .HasColumnName("penalty");

                    b.Property<double>("Points")
                        .HasColumnType("double precision")
                        .HasColumnName("points");

                    b.Property<Guid>("RanklistRowId")
                        .HasColumnType("uuid")
                        .HasColumnName("ranklist_row_id");

                    b.Property<int>("RejectedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("rejected_attempt_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_problem_results");

                    b.HasIndex("RanklistRowId", "Index")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_results_ranklist_row_id_index");

                    b.ToTable("problem_results", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.ProblemTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_translations");

                    b.HasIndex("ProblemId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_translations_problem_id_language_code");

                    b.ToTable("problem_translations", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.RanklistRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<long?>("LastSubmissionTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("last_submission_time_seconds");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("participant_type");

                    b.Property<int>("Penalty")
                        .HasColumnType("integer")
                        .HasColumnName("penalty");

                    b.Property<double>("Points")
                        .HasColumnType("double precision")
                        .HasColumnName("points");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("SuccessfulHackCount")
                        .HasColumnType("integer")
                        .HasColumnName("successful_hack_count");

                    b.Property<int>("UnsuccessfulHackCount")
                        .HasColumnType("integer")
                        .HasColumnName("unsuccessful_hack_count");

                    b.HasKey("Id")
                        .HasName("pk_ranklist_rows");

                    b.HasIndex("Handle", "ContestId", "ParticipantType")
                        .IsUnique()
                        .HasDatabaseName("ix_ranklist_rows_handle_contest_id_participant_type");

                    b.ToTable("ranklist_rows", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContestId")
                        .HasColumnType("integer")
                        .HasColumnName("contest_id");

                    b.Property<long>("CreationTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("creation_time_seconds");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("index");

                    b.Property<long>("MemoryConsumedBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("memory_consumed_bytes");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("participant_type");

                    b.Property<int>("PassedTestCount")
                        .HasColumnType("integer")
                        .HasColumnName("passed_test_count");

                    b.Property<string>("ProgrammingLanguage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("programming_language");

                    b.Property<long>("RelativeTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("relative_time_seconds");

                    b.Property<decimal>("SubmissionId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("submission_id");

                    b.Property<string>("Testset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("testset");

                    b.Property<int>("TimeConsumedMillis")
                        .HasColumnType("integer")
                        .HasColumnName("time_consumed_millis");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Verdict")
                        .HasColumnType("text")
                        .HasColumnName("verdict");

                    b.HasKey("Id")
                        .HasName("pk_submissions");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_submissions_submission_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_submissions_user_id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer")
                        .HasColumnName("complexity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("Contribution")
                        .HasColumnType("integer")
                        .HasColumnName("contribution");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<int>("FriendOfCount")
                        .HasColumnType("integer")
                        .HasColumnName("friend_of_count");

                    b.Property<int>("Grade")
                        .HasColumnType("integer")
                        .HasColumnName("grade");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("handle");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<long>("LastOnlineTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("last_online_time_seconds");

                    b.Property<string>("MaxRank")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("max_rank");

                    b.Property<int>("MaxRating")
                        .HasColumnType("integer")
                        .HasColumnName("max_rating");

                    b.Property<string>("OpenId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("open_id");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rank");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<long>("RegistrationTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("registration_time_seconds");

                    b.Property<string>("TitlePhoto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_photo");

                    b.Property<string>("VkId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vk_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Handle")
                        .IsUnique()
                        .HasDatabaseName("ix_users_handle");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProblemTag", b =>
                {
                    b.Property<Guid>("ProblemsId")
                        .HasColumnType("uuid")
                        .HasColumnName("problems_id");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_id");

                    b.HasKey("ProblemsId", "TagsId")
                        .HasName("pk_problem_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_problem_tag_tags_id");

                    b.ToTable("problem_tag", (string)null);
                });

            modelBuilder.Entity("Etrx.Domain.Models.ContestTranslation", b =>
                {
                    b.HasOne("Etrx.Domain.Models.Contest", null)
                        .WithMany("ContestTranslations")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contest_translations_contests_contest_id");
                });

            modelBuilder.Entity("Etrx.Domain.Models.Problem", b =>
                {
                    b.HasOne("Etrx.Domain.Models.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("GuidContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problems_contests_guid_contest_id");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("Etrx.Domain.Models.ProblemResult", b =>
                {
                    b.HasOne("Etrx.Domain.Models.RanklistRow", null)
                        .WithMany("ProblemResults")
                        .HasForeignKey("RanklistRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_results_ranklist_rows_ranklist_row_id");
                });

            modelBuilder.Entity("Etrx.Domain.Models.ProblemTranslation", b =>
                {
                    b.HasOne("Etrx.Domain.Models.Problem", null)
                        .WithMany("ProblemTranslations")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_translations_problems_problem_id");
                });

            modelBuilder.Entity("Etrx.Domain.Models.Submission", b =>
                {
                    b.HasOne("Etrx.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_submissions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProblemTag", b =>
                {
                    b.HasOne("Etrx.Domain.Models.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_tag_problems_problems_id");

                    b.HasOne("Etrx.Domain.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_tag_tags_tags_id");
                });

            modelBuilder.Entity("Etrx.Domain.Models.Contest", b =>
                {
                    b.Navigation("ContestTranslations");
                });

            modelBuilder.Entity("Etrx.Domain.Models.Problem", b =>
                {
                    b.Navigation("ProblemTranslations");
                });

            modelBuilder.Entity("Etrx.Domain.Models.RanklistRow", b =>
                {
                    b.Navigation("ProblemResults");
                });
#pragma warning restore 612, 618
        }
    }
}
